***Numpy***

In [ ]:
from numpy import *
import numpy
arr = array([1,2,3,5,8,9,6,7]) #array creation
print(arr)
print(__version__) #version
print(type(arr)) #class
print(arr.ndim) #Dimenstion of array
print(dir(numpy))  #print directory of numpy

[1 2 3 5 8 9 6 7]
1.22.4
<class 'numpy.ndarray'>
1
['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '

In [ ]:
a = array(1)       #0-D array(zero dimention array)
b = array([1,2,3])          #uni-dimention array(1-D array)
c = array([[1,2,3],[5,6,9]])    #2-D array(represents matrix or 2nd order tensor)                      #
d = array([[[1,2,3],[5,6,9]],[[8,9,12],[5,6,8]]])  #3-D array(used to represent 3rd order tensor)
e = array([1,2,3,4],ndmin=5)  #define no. of dimention by using ndimn argument
#Check number of dimention with the function : ndim
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d)
print(d.ndim)
print(e)
print(e.ndim)


0
1
2
[[[ 1  2  3]
  [ 5  6  9]]

 [[ 8  9 12]
  [ 5  6  8]]]
3
[[[[[1 2 3 4]]]]]
5


In [ ]:
#Access array elements
arr = array([1,2,3,4,5,6])
print(arr[0])                  #Indexing starts from 0
print('Array elements:')
for i in arr:                  #print all the elements of array
  print(i,end=' ')
print()
print('Addition of 2nd and 3ed element of array')
print(arr[1]+arr[2])

1
Array elements:
1 2 3 4 5 6 
Addition of 2nd and 3ed element of array
5


In [ ]:
#Access 2-D arrays
#Access the element on first row, second column:
two_d = array([[2,5,8,9,6,9],[8,6,5,7,1,2]])
print('2nd element on 1st row:',two_d[0,1])

#Access the element on the 2nd row, 5th column:
print('5nd element on 2st row:',two_d[1,4])

2nd element on 1st row: 5
5nd element on 2st row: 1


In [ ]:
#Access 3-D arrays
arr = array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,2])

#negative indexing
print(arr[1,-1])
print(arr[-2,-1,-3])

12
[10 11 12]
4


In [ ]:
#SLICING ARRAYS
arr = array([21,5,48,9,6,4,6,4,5,6,454,56])
print(arr[1:9])                    #[start:end]
print(arr[1:10:3])                    #[start:end:step]
print(arr[3:])                        #if end is not passed then it considers length of array
print(arr[:9])                         #if start is not passed is considers 0
print(arr[1:10])               #bydefault step is 1
print(arr[::3])

#negative indexing
print('Negative Indexing')
print(arr[-9:-2])
print(arr[-9:])


[ 5 48  9  6  4  6  4  5]
[5 6 4]
[  9   6   4   6   4   5   6 454  56]
[21  5 48  9  6  4  6  4  5]
[ 5 48  9  6  4  6  4  5  6]
[21  9  6  6]
Negative Indexing
[9 6 4 6 4 5 6]
[  9   6   4   6   4   5   6 454  56]


In [ ]:
#Slicing 2-D arrays
arr = array([[11,12,32,56,54,88],[5,2,3,6,45,45]])
print(arr[1,1:3])
print(arr[0,2:])
print(arr[0:2,1])
print(arr[0:3,1:4])



[2 3]
[32 56 54 88]
[12  2]
[[12 32 56]
 [ 2  3  6]]


**Data Types in Numpy**

'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
'''

In [ ]:
#Data Types in Numpy

'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
'''


'\ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )\n'

In [ ]:
arr = array([1,2,3,4,5])
print(arr.dtype)

int64


In [ ]:
arr = array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
#Creating Arrays With a Defined Data Type

arr = array([1,2,3,4], dtype='S')  #create array wiht data type string
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#create an array with data type 4 bytes integer
a1 = array([1,2,3,4],dtype='i4')
print(a1)
print(a1.dtype)

[1 2 3 4]
int32


If a type is given in which elements can't be casted then NumPy will raise a Value error

In [ ]:
import numpy as np

x = np.array([1,5,6,8])
mean_x = np.mean(x)
print(mean_x)


5.0


In [ ]:
#Converting data type on existing arrays
#Change data type from float to integer by using 'i' as a parameter value

import numpy as np
arr = np.array([1.1,2.2,3.3,5.5])
newarr = arr.astype('i')                      #'i' as parameter value
#newarr = arr.astype(int)                     # int as parameter value

print(newarr)
print(newarr.dtype)

[1 2 3 5]
int32


**NumPy Array Copy Vs View** The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy

In [ ]:
#Make a copy, change the original array, and print both
import numpy as np
arr = np.array([1,2,3,4,5,6])
cpyarr = arr.copy()
arr[3] = 400
cpyarr[0] = 100

print(arr)
print(cpyarr)

[  1   2   3 400   5   6]
[100   2   3   4   5   6]


In [ ]:
#Make a view, change the original array and print both
import numpy as np
arr = np.array([1,2,3,4,5,6])
varr = arr.view()
arr[3] = 400
varr[0] = 100

print(arr)
print(cpyarr)

[100   2   3 400   5   6]
[100   2   3   4   5   6]


In [ ]:
#Check if array owns its data : 'base' attribute returns 'None' if the array owns the data

import numpy as np
arr = np.array([1,2,3,4,5,6])

x = arr.copy()
y = arr.view()

print(x.base)             #copy owns the data .....output = None
print(y.base)             #view does not own the data.....otput = returns the original data

None
[1 2 3 4 5 6]


In [ ]:
#Get shape of an array : shape of an array is the number of elements in each dimention
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])         #array of 2 rows and 6 columns
print(arr.shape)              #returns (2,6), which means that the array has 2 dimentions, where the first dimension has 2 elements and second has 4

(2, 6)


In [ ]:
#create an array with 5 dimensions using 'ndmin' using a vector with values 2,5,6,4

import numpy as np
arr = np.array([2,5,6,4],ndmin = 5)
print(arr)
print('shape of array:',arr.shape)                # at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

[[[[[2 5 6 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [ ]:
#Reshaping array : Changing the shape of an array
#reshape from 1-D to 2-D & 3-D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)    #2-D
newarr1 = arr.reshape(2,3,2)   #3-D
print(newarr)
print(newarr.shape)
print(newarr1)
print(newarr1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [ ]:
#Check if the returned  array  is a copy or view

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.reshape(2,5).base)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Unknown dimension
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
newarr = arr.reshape(5,2,-1)                 #We can not pass -1 to more than 1 dimension
print(newarr)

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]]


In [ ]:
#Flattering the arrays : Converting multi dimensional array into one dimensional array : Use (reshape(-1))
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
newarr = arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Iterating arrays : Iterating array means going through one by one element of array
import numpy as np
arr = np.array([1,2,3,4,5,6])
for i in arr:
  print(i)

1
2
3
4
5
6


In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,8,9,6]],[[8,6,3,4],[1,2,3,8]]])
for x in arr:                 #Going through lists only
  print(x)
for x in arr:
  for y in x:                 #Going through the each element of both the lists
    for z in y:
      print(z)


[[1 2 3 4]
 [5 8 9 6]]
[[8 6 3 4]
 [1 2 3 8]]
1
2
3
4
5
8
9
6
8
6
3
4
1
2
3
8


In [ ]:
#Iterarting arrays using nditet() : a function used for basic to advanced iterations.
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[8,9]]])
for i in np.nditer(arr):
  print(i)

1
2
3
4
5
6
8
9


In [ ]:
#Joining numpy arrays : concatenate()
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
#join 2-D arrays
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#joining arrays using stack() function
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.hstack((arr1,arr2))   #Stacking along rows hstack()
print('Stack along Rows:',arr3)
arr4 = np.vstack((arr1,arr2))     #Stacking along columns vstack()
print('Stack along Columns:')
print(arr4)
print('Stack along Height:')
arr5 = np.dstack((arr1,arr2))
print(arr5)

Stack along Rows: [1 2 3 4 5 6 7 8]
Stack along Columns:
[[1 2 3 4]
 [5 6 7 8]]
Stack along Height:
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [ ]:
#Splitting arrays : Splitting is nothing a exact opposite to joining : array_split()
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr,3)
#newarr = np.array_split(arr,5)          #if the array has less elements than required, it will adjust the end accordingly
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#Searching arrays : where()
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
np.where(arr == 4)             #index value for all the 4 will be return in tuple

(array([3, 5, 6]),)

In [ ]:
#find the index where the values are even
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 18,16,5,7,36])
np.where(arr%2 == 0)

(array([ 1,  3,  5,  6,  7, 10]),)

In [ ]:
#find the index where the values are odd
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 18,16,5,7,36])
np.where(arr%2 == 1)

(array([0, 2, 4, 8, 9]),)

In [ ]:
#sorting arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 18,16,5,7,36])
np.sort(arr)

array([ 1,  2,  3,  4,  4,  5,  5,  7, 16, 18, 36])

In [ ]:
#sort array of string
import numpy as np
arr = np.array(['banana', 'cherry', 'apple','grapes'])
np.sort(arr)

array(['apple', 'banana', 'cherry', 'grapes'], dtype='<U6')

In [ ]:
#filter array that will return values greater than 35
import numpy as np
arr =np.array([25,3,5,65,45,82,1,2,00,12,0,122,4,44,5,22,11,55,11,52,445,1,1,1225,44,1212,1])
fltrarr = []
for i in arr:
  if i >35:
    fltrarr.append(i)
print(fltrarr)

[65, 45, 82, 122, 44, 55, 52, 445, 1225, 44, 1212]


In [ ]:
#filter array that will return even values only
import numpy as np
arr =np.array([25,3,5,65,45,82,1,2,00,12,0,122,4,44,5,22,11,55,11,52,445,1,1,1225,44,1212,1])
fltrarr = []
for i in arr:
  if (i%2 == 0):
    fltrarr.append(i)
print(fltrarr)

[82, 2, 0, 12, 0, 122, 4, 44, 22, 52, 44, 1212]


In [ ]:
#Import library
import numpy as np

In [ ]:
#Create ND array
nd_array = np.array([1,2,3,4])
print(nd_array)

[1 2 3 4]


In [ ]:
#Array with zeros
ar_with_zeros = np.zeros((3,3))
print(ar_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Array with ones
ar_with_ones = np.ones((2,3))
print(ar_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Empy array
empty_ar = np.empty((1,2))
print(empty_ar)

[[7.74860419e-304 7.74860419e-304]]


In [ ]:
#Array with arrange method
#one dimensional array
np_arange = np.arange(15)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#reshape method to change /create array
np_arange.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])